### ISSUE TITLE
Toggle field with toggleid not working and browse() also not working

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#15]
HI @kompo 

I using Toggle field like below to show/hide a panel

```
Toggle::form('Enable Filter')->toggleId('filter-panel'),
            Panel::form(
                Columns::form(
                    Input::form('Filter by Keyword')->name('keyword')->filter(),
                    Input::form('Filter by Freq')->name('freq')->filter('>='),
                    Input::form('Filter by Slug')->name('slug')->filter(),
                ),
                Button::form("Clear Filter")->refresh()->browse(),
            )->id('filter-panel')
```
But it not work, in html on client display:none not remove when toggle on
```
<div id="filter-panel" class="vlPanel vlFormPanel" style="display: none;">
```

method browse() also not working, refresh() help clear input (filters) but not reload Cards of current Query 

Thanks in advance,

**Comment by kompo** [comment]
Hi, 

These issues have been fixed in [https://github.com/kompo/vue-kompo/commit/5b655069d1e971e3b5a51d186212ba7c96e45c09](https://github.com/kompo/vue-kompo/commit/5b655069d1e971e3b5a51d186212ba7c96e45c09)

If you are using npm packge, please update to vue-kompo@2.0.5 for these changes to work.

Also, you can remove `->browse()` as it is no longer necessary. Using `->refresh()` will reset filters and cards of query.

Let me know if it works for you.

**Comment by xnohat** [comment]
Hi @kompo,

bugs still not fix 😥 .

my package.json and I sure has updated to vue-kompo@2.0.6 (deleted node_modules and npm install again)
```
 "dependencies": {
        "@postlight/mercury-parser": "^2.2.0",
        "vue-kompo": "^2.0.6"
    }
```

Below is full of my query

```
<?php

namespace App\Http\Komposers;

use Kompo\{Table, Th, Html, EditLink, AddLink, DeleteLink, Title, Input, Button, Select, MultiSelect, Toggle, Columns, Panel, Link, FlexBetween};
use Illuminate\Support\Facades\DB;
use App\Models\Tags; //just use this model instead spatie tag model because it need deletable method
use App\Models\Topics;
use App\Models\Keywords;
use Illuminate\Support\Carbon;

class NewsTrendingQuery extends Table
{
    public $perPage = 20; //The amount of items per page.
    public $noItemsFound = 'No items found'; //The message to display when no items are found.

    public $hasPagination = true; //Whether to display pagination links or not
    public $topPagination = true; //Whether to display pagination links above the cards
    public $bottomPagination = true; //Whether to display pagination links below the cards
    public $leftPagination = false; //Whether to align pagination links to the left or to the right

    public $paginationStyle = 'Links'; //The pagination component. Other option is 'Showing'


    public function query()
    {
        //return Keywords::whereDate('created_at', '>=', Carbon::today()->toDateString())->get();
        return DB::table('keywords')
                ->select('id','keyword','slug','created_at', DB::raw('count("keyword") as freq'))
                ->where('created_at', '>=', Carbon::now()->subHours(6))
                ->groupBy('keyword')
                ->orderBy('freq','DESC');
    }

    public function headers()
    {
        return [
            Th::form('Keywords'),
            Th::form('Freq'),
            Th::form('Slug'),
            Th::form('Created At'),
            Th::form()->icon('fas fa-search'),
        ];
    }

    public function card($item)
    {
    	return [
    	    // Card Komponents
            Html::form($item->keyword)->class('font-bold'),
            Html::form($item->freq),
            Html::form($item->slug),
            Html::form($item->created_at),
            Link::form()->icon('fas fa-search')->getKomposer(TopicsTrendingQuery::class, ['keywordslug' => $item->slug, 'keyword' => $item->keyword])->inModal(),
            //->url(route('topics-trending-list',['keywordslug' => $item->slug]))
    	];
    }

    public function top()
	{
		return [
            FlexBetween::form(
                Title::form('News Trend (News Supply)')->style('font-size: 3vmax'),
            ),
            Toggle::form('Enable Filter')->toggleId('filters'),
            Panel::form(
                Columns::form(
                    Input::form('Filter by Keyword')->name('keyword')->filter(),
                    Input::form('Filter by Freq')->name('freq')->filter('>='),
                    Input::form('Filter by Slug')->name('slug')->filter(),
                ),
                Button::form("Clear Filter")->refresh(),
                //Link::form('Clear Filter')->url(route('news-trending-list'))->button(),
            )->id('filters'),
            //Link::form('Filter')->icon('fas fa-cogs')->toggleId('filters'),
		];
	}
}
```

P.s: Could you please help me some examples in use browse() method to reload cards of query ?

**Comment by kompo** [comment]
Hi, 

I tested your code again and it is working for me. **What is the error you are getting?** 

Note that I changed one thing: I added ->ignoresModel() to Toggle field. Without it Kompo will think it is one of the Model's attributes:

```
Toggle::form('Enable Filter')->ignoresModel()->toggleId('filters'),
```
Make sure to rebuild and hard refresh your browser...

As for the browse example, you can use it after you make a backend change for example:

```
_Button('Set as Default')
         ->selfPost('setDefaultSignature', ['id' => $item->id])
        ->browse()
```

Or you can use it from another Form to browse a Query with it's id:

```
_SubmitButton('Save')->browse('message-signatures-query')
````

**Comment by kompo** [comment]
@xnohat I just fixed another bug regarding Toggle (it was toggling twice). [https://github.com/kompo/vue-kompo/commit/cbed47e545a4292bcb823970287a4a4b76954637](https://github.com/kompo/vue-kompo/commit/cbed47e545a4292bcb823970287a4a4b76954637)

I hope this is your issue. Please use vue-kompo@2.0.7

**Comment by xnohat** [comment]
> @xnohat I just fixed another bug regarding Toggle (it was toggling twice). [kompo/vue-kompo@cbed47e](https://github.com/kompo/vue-kompo/commit/cbed47e545a4292bcb823970287a4a4b76954637)
> 
> I hope this is your issue. Please use vue-kompo@2.0.7

Thanks @kompo toggle has been working (display and none properly) !
But another bug related to toggle. When using Toggle for toggle inputs use for filters, it make all filters return nothing

below is an request/response from filter after using toggle for filter input field

```
POST /_kompo HTTP/1.1
Host: www.tinsang.net
Connection: keep-alive
Content-Length: 621
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
X-Kompo-Action: browse-many
X-XSRF-TOKEN: eyJpdiI6InpCQ1JsTHVCTW5MUWU2RGl0Y2UzdlE9PSIsInZhbHVlIjoiYzBZWHBtR1Y3VzNtNm9RdXJGSlZKN1ozdmJha3JUeERGQTZzckFFVjZhT0pDVEEzSUlUU2dORDFMWTlpWE56MUQ5SVA3MEZmM1hNVHZoY2R3K2M1SG5XcE9jekFsME5pR1hMdjFWUzlVRU54Z29aTGc4VUNOaVhSdE1wcFA2VjUiLCJtYWMiOiI1ODQzZTI1MTE0NzgyZTY3MTBmM2ZhMjQyMzQ5N2RlZjk2NDJkM2U2NWQwNzIwN2RkYjAyYjdiMmZkZWI1ODE3In0=
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: http://www.tinsang.net
Referer: http://www.tinsang.net/news-trending
Accept-Encoding: gzip, deflate
Accept-Language: vi,en-US;q=0.9,en;q=0.8
Cookie: remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkdqRjNpempvWkN5ZkV4V0o1QjFqZ0E9PSIsInZhbHVlIjoiMFlwZGk3M1YwTHZlT0xvdGViNHl3MWU2eU9wS0dUTElZRUVMczdqelM1MGlCNVVrV28zN2k4eURzRXhCQWFBM1pwMWlLbFlzZlBUMDdDWXBaQ1pCUGZ6ZGcwTU1Pem5STWZDNmdHV3UyNUVZdzIvRWNhV0szYUZ2aDhhUDBLWlJqMW03cW9JR1ViNXo4ZStrL0NZdWkyNVRUc2s3T1NGS2FMZ1FOQ1FtcnY2V1M4S08vckJmMnJPVENFdnEwMmtBanBTQmVOZDZHVm12NHdjNFllMXc2ZjVwcG11VGxWMlhwRm5xR1ZQVUV6VT0iLCJtYWMiOiI0ZmNhMTVmMzI5MzQ1M2JhNWQyNWQyY2JlYzgyOTlmYzE5NjI0MGNhZDcwNDI5MDBlMTdjNjZlMWNkYjQ5ZGJlIn0%3D; XSRF-TOKEN=eyJpdiI6InpCQ1JsTHVCTW5MUWU2RGl0Y2UzdlE9PSIsInZhbHVlIjoiYzBZWHBtR1Y3VzNtNm9RdXJGSlZKN1ozdmJha3JUeERGQTZzckFFVjZhT0pDVEEzSUlUU2dORDFMWTlpWE56MUQ5SVA3MEZmM1hNVHZoY2R3K2M1SG5XcE9jekFsME5pR1hMdjFWUzlVRU54Z29aTGc4VUNOaVhSdE1wcFA2VjUiLCJtYWMiOiI1ODQzZTI1MTE0NzgyZTY3MTBmM2ZhMjQyMzQ5N2RlZjk2NDJkM2U2NWQwNzIwN2RkYjAyYjdiMmZkZWI1ODE3In0%3D; laravel_session=eyJpdiI6ImwvTVVnaE9nTlZETG1kU2J1dWtqT2c9PSIsInZhbHVlIjoiY3NSbiszOWdUeWJvUmlSR1BlZHM5aVJmeDNGNEtWSGY0NVRXMUxiTFZqek41SmJ5SUM1UTJhRHhvajlUUGtqcm93aFdDd25jZGliM3M0WGZZWlRxaHFJNTR3c0ZINXVvWGgxY1pZQ0hZZXNBRmZMN1FuMzJzeS9zVGNsWGxsdmYiLCJtYWMiOiJjNmIwOTljNjQwY2JiZjg4Yjc0YTdlOGQwNzFiODE5NTZmYjQ1Njc0NzY2ZTg4OTZlMTQ4MTcxZTEzMDQ3Y2ZjIn0%3D

```

Response

```
{"NewsTrendingQuery60b281c59483e":{"current_page":1,"data":[],"first_page_url":"\/?page=1","from":null,"last_page":1,"last_page_url":"\/?page=1","links":[{"url":null,"label":"&laquo; Previous","active":false},{"url":"\/?page=1","label":"1","active":true},{"url":null,"label":"Next &raquo;","active":false}],"next_page_url":null,"path":"\/","per_page":20,"prev_page_url":null,"to":null,"total":0}}
```

-----------

Another question, where I can set Query ID for using in ->browse('query-id') ? I checked document but not know how to define it :( 

Many thanks for your time,

**Comment by kompo** [comment]
@xnohat you can set the id of a query like so:

**Method 1**
Set the public `$id` property directly.

```
class NewsTrendingQuery extends Query
{
    public $id = 'news-trending-query';
}
```

**Method 2**
or in the created phase with the `->id()` method (useful when you have many queries on the same page and your id is a variable or depends on some parameter):


```
class NewsTrendingQuery extends Query
{
    public function created()
    {
        $this->id('news-trending-query-'.$this->parameter('category'));
    }
}
```
This allows you to browse/refresh the query from **outside the class**. This can be useful if you have a Form and Query on the same page and you want to refresh the query after a form submit.

```
_Button()->submit()->browse('news-trending-query')
```

As for the _Toggle bug, I am sorry but I don't understand the issue. Not enough information. Are you sure you added ->ignoresModel() on the _Toggle? I tried your example again and it works even with query() method returning Eloquent Builder, Database Builder and Collection... I usually debug query filters problems with this [https://github.com/kompo/kompo/blob/master/src/Komposers/Query/QueryFilters.php#L70](https://github.com/kompo/kompo/blob/master/src/Komposers/Query/QueryFilters.php#L70), maybe it will help you find your issue.

Let me know if you have other questions or more information on the issue.

**Comment by xnohat** [comment]
Oh I got it
```
added ->ignoresModel() on the _Toggle
```
Fixed problem with filter() on other fields, we need ignoresModel on any fields not interact with eloquent.

My Applications worked perfectly, Kompo boost development speed !

Thanks for your support and time @kompo
